//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_PCR18.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General_PCR18.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 化验类型.
        /// </summary>
        public static string assay_type {
            get {
                return ResourceManager.GetString("assay_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 实验参数.
        /// </summary>
        public static string analysis_parameters {
            get {
                return ResourceManager.GetString("analysis_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string btn_browse {
            get {
                return ResourceManager.GetString("btn_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据分析.
        /// </summary>
        public static string data_analyse {
            get {
                return ResourceManager.GetString("data_analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试管检测结果存储路径.
        /// </summary>
        public static string data_result_path {
            get {
                return ResourceManager.GetString("data_result_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩增曲线(DeltaRn).
        /// </summary>
        public static string delta_rn {
            get {
                return ResourceManager.GetString("delta_rn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩增曲线(规一化).
        /// </summary>
        public static string delta_rn_normalize {
            get {
                return ResourceManager.GetString("delta_rn_normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原始扩增曲线.
        /// </summary>
        public static string delta_rn_original {
            get {
                return ResourceManager.GetString("delta_rn_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管号.
        /// </summary>
        public static string dock_unit {
            get {
                return ResourceManager.GetString("dock_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实验.
        /// </summary>
        public static string experiment {
            get {
                return ResourceManager.GetString("experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部导出.
        /// </summary>
        public static string export_all {
            get {
                return ResourceManager.GetString("export_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择导出.
        /// </summary>
        public static string export_select {
            get {
                return ResourceManager.GetString("export_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问此文件.
        /// </summary>
        public static string file_cannot_access {
            get {
                return ResourceManager.GetString("file_cannot_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1 温度.
        /// </summary>
        public static string h1_temperature {
            get {
                return ResourceManager.GetString("h1_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1 时间.
        /// </summary>
        public static string h1_time {
            get {
                return ResourceManager.GetString("h1_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H3 温度.
        /// </summary>
        public static string h3_temperature {
            get {
                return ResourceManager.GetString("h3_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H3 时间.
        /// </summary>
        public static string h3_time {
            get {
                return ResourceManager.GetString("h3_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加热检测.
        /// </summary>
        public static string heating_detection {
            get {
                return ResourceManager.GetString("heating_detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登录.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎使用.
        /// </summary>
        public static string login_welcome {
            get {
                return ResourceManager.GetString("login_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否退出软件？.
        /// </summary>
        public static string logout_confirm {
            get {
                return ResourceManager.GetString("logout_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接仪器失败，请确认仪器已经连接。.
        /// </summary>
        public static string msg_connect_failed {
            get {
                return ResourceManager.GetString("msg_connect_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入不超过一位的小数！.
        /// </summary>
        public static string msg_decimal_one_error {
            get {
                return ResourceManager.GetString("msg_decimal_one_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 孔位试管已拔出，检测终止！.
        /// </summary>
        public static string msg_hole_pull_out {
            get {
                return ResourceManager.GetString("msg_hole_pull_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器识别中….
        /// </summary>
        public static string msg_identify_instrument {
            get {
                return ResourceManager.GetString("msg_identify_instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入正整数！.
        /// </summary>
        public static string msg_int_error {
            get {
                return ResourceManager.GetString("msg_int_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到仪器.
        /// </summary>
        public static string msg_no_instrument_detected {
            get {
                return ResourceManager.GetString("msg_no_instrument_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败.
        /// </summary>
        public static string msg_op_error {
            get {
                return ResourceManager.GetString("msg_op_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停会清空数据，是否暂停?.
        /// </summary>
        public static string msg_pause_lighting {
            get {
                return ResourceManager.GetString("msg_pause_lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新开始会清空数据，是否开始？.
        /// </summary>
        public static string msg_restart_lighting {
            get {
                return ResourceManager.GetString("msg_restart_lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止{0}孔位试管实验.
        /// </summary>
        public static string msg_stop_experiment {
            get {
                return ResourceManager.GetString("msg_stop_experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string msgbox_title {
            get {
                return ResourceManager.GetString("msgbox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 患者ID.
        /// </summary>
        public static string patient_id {
            get {
                return ResourceManager.GetString("patient_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCR 设置.
        /// </summary>
        public static string pcr_setting {
            get {
                return ResourceManager.GetString("pcr_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行程序.
        /// </summary>
        public static string program_run {
            get {
                return ResourceManager.GetString("program_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行监控.
        /// </summary>
        public static string run_monitor {
            get {
                return ResourceManager.GetString("run_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本ID.
        /// </summary>
        public static string sample_id {
            get {
                return ResourceManager.GetString("sample_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阴性对照.
        /// </summary>
        public static string sample_negative {
            get {
                return ResourceManager.GetString("sample_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无模板对照.
        /// </summary>
        public static string sample_ntc {
            get {
                return ResourceManager.GetString("sample_ntc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阳性对照.
        /// </summary>
        public static string sample_positive {
            get {
                return ResourceManager.GetString("sample_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本登记.
        /// </summary>
        public static string sample_regiration {
            get {
                return ResourceManager.GetString("sample_regiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准品.
        /// </summary>
        public static string sample_standard {
            get {
                return ResourceManager.GetString("sample_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本类型.
        /// </summary>
        public static string sample_type {
            get {
                return ResourceManager.GetString("sample_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待测样品.
        /// </summary>
        public static string sample_unknown {
            get {
                return ResourceManager.GetString("sample_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准曲线.
        /// </summary>
        public static string standard_curve {
            get {
                return ResourceManager.GetString("standard_curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 化验类型.
        /// </summary>
        public static string tbh_assay {
            get {
                return ResourceManager.GetString("tbh_assay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道.
        /// </summary>
        public static string tbh_channels {
            get {
                return ResourceManager.GetString("tbh_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string tbh_color {
            get {
                return ResourceManager.GetString("tbh_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浓度.
        /// </summary>
        public static string tbh_concentration {
            get {
                return ResourceManager.GetString("tbh_concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准品浓度.
        /// </summary>
        public static string tbh_concentration_st {
            get {
                return ResourceManager.GetString("tbh_concentration_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结论.
        /// </summary>
        public static string tbh_conclusions {
            get {
                return ResourceManager.GetString("tbh_conclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ct.
        /// </summary>
        public static string tbh_ct {
            get {
                return ResourceManager.GetString("tbh_ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前加热器.
        /// </summary>
        public static string tbh_current_heater {
            get {
                return ResourceManager.GetString("tbh_current_heater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管号.
        /// </summary>
        public static string tbh_dock_unit {
            get {
                return ResourceManager.GetString("tbh_dock_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string tbh_endtime {
            get {
                return ResourceManager.GetString("tbh_endtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加热剩余时间.
        /// </summary>
        public static string tbh_heat_time_remain {
            get {
                return ResourceManager.GetString("tbh_heat_time_remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string tbh_no {
            get {
                return ResourceManager.GetString("tbh_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string tbh_notes {
            get {
                return ResourceManager.GetString("tbh_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目名称.
        /// </summary>
        public static string tbh_project_name {
            get {
                return ResourceManager.GetString("tbh_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本ID.
        /// </summary>
        public static string tbh_sample_id {
            get {
                return ResourceManager.GetString("tbh_sample_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本名称.
        /// </summary>
        public static string tbh_sample_name {
            get {
                return ResourceManager.GetString("tbh_sample_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样本类型.
        /// </summary>
        public static string tbh_sample_type {
            get {
                return ResourceManager.GetString("tbh_sample_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string tbh_starttime {
            get {
                return ResourceManager.GetString("tbh_starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标信息.
        /// </summary>
        public static string tbh_target {
            get {
                return ResourceManager.GetString("tbh_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余时间.
        /// </summary>
        public static string tbh_time_remaining {
            get {
                return ResourceManager.GetString("tbh_time_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tm1.
        /// </summary>
        public static string tbh_tm1 {
            get {
                return ResourceManager.GetString("tbh_tm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tm2.
        /// </summary>
        public static string tbh_tm2 {
            get {
                return ResourceManager.GetString("tbh_tm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反应孔.
        /// </summary>
        public static string tbh_well {
            get {
                return ResourceManager.GetString("tbh_well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 温度曲线.
        /// </summary>
        public static string temperature_curve {
            get {
                return ResourceManager.GetString("temperature_curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检验日期.
        /// </summary>
        public static string test_date {
            get {
                return ResourceManager.GetString("test_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阈值.
        /// </summary>
        public static string threshold {
            get {
                return ResourceManager.GetString("threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余时长:.
        /// </summary>
        public static string time_remaining {
            get {
                return ResourceManager.GetString("time_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试管检测时长.
        /// </summary>
        public static string tube_detection_time {
            get {
                return ResourceManager.GetString("tube_detection_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string user_manage {
            get {
                return ResourceManager.GetString("user_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码不能为空.
        /// </summary>
        public static string username_password_empty {
            get {
                return ResourceManager.GetString("username_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码错误.
        /// </summary>
        public static string username_password_error {
            get {
                return ResourceManager.GetString("username_password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户存储路径.
        /// </summary>
        public static string user_path {
            get {
                return ResourceManager.GetString("user_path", resourceCulture);
            }
        }
    }
}
